id: PD039A665
initial_creation_type: input
source_metadata:
  Title: Pārājikā (Texts from Nepal)
  Editor: M. G. Dhadphale
  Publisher: Bhandarkar Oriental Research Institute
  Place of Publication: Savitri Prakashan, Pune 30
  Year: '2013'
  लोकेश्वर-पाराजिका:
    Text Version: Devanagari
    Input Personnel: Bibek Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:09:45.711083'
last_modified_at: '2022-03-08T17:09:45.711093'
